version: "3"

services:
#
#  backend:
#    container_name: multi_backend
#    build: ./backend/
#    ports:
#      - "4000:5000"
#    networks:
#      - gitlab

#  frontend:
#    container_name: multi_frontend
#    build: ./frontend/
#    image: frontend
#    ports:
#      - "3000:5000"
#    networks:
#      - gitlab

#  test_testend:
#    container_name: multi_testend
#    build: ./testend/inner
#    ports:
#      - "3000:5000"
#    networks:
#      - gitlab

  extern_http:
    image: thriqon/alpine-darkhttpd
    ports:
      - "8081:80"

  extern_tcp:
    image: cjimti/go-echo
    environment:
      - TCP_PORT=2701
      - NODE_NAME="extern_tcp"
    ports:
      - "1234:2701"

  simple_http:
    build: ./simple_http/
    image: simple_http
    ports:
      - "8080:80"

  simple_tcp:
    build: ./simple_tcp/
    image: simple_tcp
    environment:
      - TCP_PORT=2701
      - NODE_NAME="simple_tcp"
    ports:
      - "4321:2701"

networks:
  gitlab: