version: "3"

services:
#
#  backend:
#    container_name: multi_backend
#    build: ./backend/
#    ports:
#      - "4000:5000"
#    networks:
#      - gitlab

#  frontend:
#    container_name: multi_frontend
#    build: ./frontend/
#    image: frontend
#    ports:
#      - "3000:5000"
#    networks:
#      - gitlab

#  test_testend:
#    container_name: multi_testend
#    build: ./testend/inner
#    ports:
#      - "3000:5000"
#    networks:
#      - gitlab

  simple_http:
    build: ./simple_http/
    image: simple_http
    ports:
      - "8080:80"

  simple_tcp:
    build: ./simple_tcp/
    image: simple_tcp
    environment:
      - TCP_PORT=2701
      - NODE_NAME="EchoNode"
    ports:
      - "3000:5000"

networks:
  gitlab: