version: "3"

services:

  extern_http:
    image: thriqon/alpine-darkhttpd
    ports:
      - "8081:80"
    volumes:
      - ./flags/chal1:/www/flag.txt:ro
    labels:
      kompose.service.expose: "true"

#  extern_tcp:
#    image: cjimti/go-echo
#    environment:
#      - TCP_PORT=2701
#      - NODE_NAME="extern_tcp"
#    ports:
#      - "1234:2701"
#    volumes:
#      - ./flags/chal2:/flag.txt:ro
#    labels:
#      kompose.service.type: nodeport
#
#  simple_http:
#    build: ./simple_http/
#    image: simple_http
#    ports:
#      - "8080:80"
#    volumes:
#      - ./flags/chal2:/www/flag.txt:ro
#    labels:
#      kompose.service.expose: "true"
#
#  simple_tcp:
#    build: ./simple_tcp/
#    image: simple_tcp
#    environment:
#      - TCP_PORT=2701
#      - NODE_NAME="simple_tcp"
#    ports:
#      - "4321:2701"
#    volumes:
#      - ./flags/chal2:/flag.txt:ro
#    labels:
#      kompose.service.type: nodeport


      # TODO use secrets instead of bind mounts
#    secrets:
#      - source: my_secret
#        target: /redis_secret
#        uid: '103'
#        gid: '103'
#        mode: 0440
#
#secrets:
#  my_secret:
#    file: ./my_secret.txt
