version: "3.8"

services:

  kdfd_testing_challenge_helper:
    image: thriqon/alpine-darkhttpd
    volumes:
      - ./flags:/flags

  extern_http:
    image: thriqon/alpine-darkhttpd
    ports:
      - "8081:80"
    volumes:
      - ./flags/chal1:/www/flag.txt:ro

  extern_tcp:
    image: cjimti/go-echo
    environment:
      - TCP_PORT=2701
      - NODE_NAME="extern_tcp"
    ports:
      - "1234:2701"
    volumes:
      - ./flags/chal2:/flag.txt:ro

  simple_http:
    build: ./simple_http/
    image: simple_http
    ports:
      - "8080:80"
    volumes:
      - ./flags/chal2:/www/flag.txt:ro

  simple_tcp:
    build: ./simple_tcp/
    image: simple_tcp
    environment:
      - TCP_PORT=2701
      - NODE_NAME="simple_tcp"
    ports:
      - "4321:2701"
    volumes:
      - ./flags/chal2:/flag.txt:ro

networks:
  gitlab:
