version: "3"
services:
  backend:
    container_name: basejumper_backend
    build: ./backend/
    ports:
      - "8085:8080"
    networks:
      - gitlab
  srv3:
    container_name: basejumper_srv3
    build: ./frontend/
    networks:
      - gitlab
  frontend:
    container_name: basejumper_frontend
    build: ./frontend/
    ports:
      - "8084:80"
    networks:
      - gitlab

networks:
  gitlab: