apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: extern-http
  name: extern-http
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: extern-http
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: extern-http
    spec:
      containers:
        - image: thriqon/alpine-darkhttpd
          name: extern-http
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /www/flag.txt
              name: extern-http-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: extern-http-claim0
          persistentVolumeClaim:
            claimName: extern-http-claim0
            readOnly: true
status: {}
