apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: simple-tcp
  name: simple-tcp
spec:
  ports:
    - name: "4321"
      port: 4321
      targetPort: 2701
  selector:
    io.kompose.service: simple-tcp
status:
  loadBalancer: {}
