apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: simple-tcp
  name: simple-tcp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: simple-tcp
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: simple-tcp
    spec:
      containers:
        - env:
            - name: NODE_NAME
              value: '"simple_tcp"'
            - name: TCP_PORT
              value: "2701"
          image: simple_tcp
          name: simple-tcp
          ports:
            - containerPort: 2701
          resources: {}
      restartPolicy: Always
status: {}
