apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.service.expose: myurl.lol
  creationTimestamp: null
  labels:
    io.kompose.service: simple-http
  name: simple-http
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: simple-http
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.service.expose: myurl.lol
      creationTimestamp: null
      labels:
        io.kompose.service: simple-http
    spec:
      containers:
        - image: simple_http
          name: simple-http
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
